### ISSUE TITLE
Retina images

### ISSUE THREAD

**Issue by tracend** [commons/less#6]
Although the js portion of retina.js is imo an unnecessary client side dependency, the Less helper seems like a reasonable solution for stylesheets: 
https://github.com/imulus/retinajs/blob/master/src/retina.less 

Consider including it in the commons lib

**Comment by ryndel** [comment]
I like this version because it allows you to create either a repeating or non repeating background image.
Usage is as follows:

.image-logo {
    width: 100px;
    height: 50px;
    .retina-2x('image.png', 100px, 50px);
}

.repeating-background-image {
    background-color: #444;
    .retina-2x('image.png', 200px, 200px, repeat);
}
